### ISSUE TITLE
抓取评论的时候，会被检测到是爬虫行为

### ISSUE THREAD

**Issue by autodataming** [hunterhug/taobaocomment#3]
抓到35页后会被检测到爬虫行为
https://rate.tmall.com/list_detail_rate.htm?itemId=44885077157&sellerId=2456386471&content=1&order=3&currentPage=35
cookie: t=e4c18cfa9a96c304df83d29e292a8f10; thw=cn; cna=bjoSENsh0hwCAcp/EwV1bje5; l=AkdHq51PO48Z3TRljsGLpE/09/URTBsu; isg=AgQE82lMAFU4fbuSWO
x=e%3D1%26p%3D*%26s%3D0%26c%3D0%26f%3D0%26g%3D0%26t%3D0%26__ll%3D-
{{"rgv587_flag":"sm","url":"https://sec.taobao.com/query.htm?style=mini&smApp=tmallrateweb&smPolicy=tmallrateweb-rate-anti_Spider-checkcode&
smCharset=GBK&smTag=MjAyLjEyNy4xOS4yLDE5MDQ2MTI2MCwzMjI1YmU2NTlmYWY0YTQwOWMyMzU3NTYzYTIyMTY3NA%3D%3D&smReturn=https%3A%2F%2Frate.tmall.com%2
Flist_detail_rate.htm%3FitemId%3D44885077157%26sellerId%3D2456386471%26content%3D1%26order%3D3%26currentPage%3D35&smSign=X9C3hFxJBDeZeK275tI
rxg%3D%3D"}}

**Comment by hunterhug** [comment]
应该是没暂停所致，天猫反爬不确定
